tryCatch({
  # print(Sys.time())
  # Sys.sleep(120)
  # print(Sys.time())
  # Sys.sleep(120)
  # print(Sys.time())
  # Sys.sleep(120)
  # print(Sys.time())
  # Sys.sleep(120)
  # print(Sys.time())
  # Sys.sleep(120)
  # print(Sys.time())
  # Sys.sleep(120)
  print(Sys.time())
  Sys.sleep(660)
})

# This never timed out.  Even when being sourced.  I do not understand why I was running into timeout errors
# on my other PC.

# Now changed it to run with an eleven minute delay.  We'll see what happens.